services:
  chirpstack-gateway-os:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - /home/jenkins-user/jenkins-workspace/osi:/workdir
    ulimits:
      nofile:
        soft: 1024
        hard: 262144
    environment:
      - QUILT_PATCHES=/workdir/conf/patches
