services:
  chirpstack-gateway-os:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ${PWD}:/workdir  # Use environment variable instead of .
    ulimits:
      nofile:
        soft: 1024
        hard: 262144
    environment:
      - QUILT_PATCHES=/workdir/conf/patches